# Website settings
url: "https://hanbnrd.github.io" # the base hostname & protocol for your site (e.g. http://example.com)
baseurl: "/Horizon" # the subpath of your site (e.g. /blog)
title: "Horizon" # the name of your site

# User settings
name: Horizon Template
about: Responsive personal website
email: ""
github: ""
gitlab: ""
linkedin: ""
twitter: ""

# Asset settings
picture: picture.jpg
qr-code: qrcode.png
# background-video: background.mp4
# background-video-thumbnail: background-thumbnail.jpg
background-image: background.jpg
